# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  pull_request:
  push:
    branches:
      - master
  schedule:
    - cron: "0 4 * * 4"

permissions:
  contents: read

# please track https://github.com/ansible-collections/news-for-maintainers/issues/28

jobs:
  sanity:

    runs-on: ubuntu-latest

    steps:
      - name: Perform sanity testing with ansible-test
        uses: ansible-community/ansible-test-gh-action@release/v1
        with:
          # start off with 2.16 and then close in to what https://github.com/ansible-collections/community.general is using
          ansible-core-version: stable-2.16
          testing-type: sanity
      
      - name: create a fake incus cli and test it
        run: |
          echo '#!/bin/bash' > /usr/local/bin/incus
          echo 'echo "incus is currently a fake"' >> /usr/local/bin/incus
          chmod +x /usr/local/bin/incus

      - name: Perform unit testing with ansible-test
        uses: ansible-community/ansible-test-gh-action@release/v1
        with:
          ansible-core-version: stable-2.26
          # pre-test-cmd: echo This runs before the ansible-test invocation
          target-python-version: 3.11
          testing-type: units
          test-deps: >-
            ansible.netcommon
            ansible.utils
